language: python

python:
    - "2.7"
    - "3.2"

virtualenv:
  system_site_packages: true

# Enable container-based infrastructure
sudo: false

  # install dependencies
addons:
  apt:
    packages:
      - python-requests
      - python3-requests

install:
  - pip install -r requirements.txt

script:
  # Alternative: setup.py install.
  # Using pip makes sure that the package is pip-compatible, too.
  - pip install .
  - betterbib -h
