language: python

python:
    - "2.7"
    - "3.4"

virtualenv:
  system_site_packages: true

# Enable container-based infrastructure
sudo: false

install:
  - pip install -r requirements.txt
  # Alternative: setup.py install.
  # Using pip makes sure that the package is pip-compatible, too.
  - pip install .
