#!/usr/bin/env python
# -*- coding: utf8 -*-

import re
import xml.etree.ElementTree as ET
# -----------------------------------------------------------------------------
def _main():

    args = _parse_cmd_arguments()
    infile = args.infile

    data = _read_bibtex(infile)

    # Open output file for writing.
    out = open(args.outfile, 'w')

    n = len(data.entries)
    k = 0
    success_count = 0
    for bib_id in data.entries:
        k += 1
        b = data.entries[bib_id].fields
        title = b['title']
        title = title.replace('{', '')
        title = title.replace('}', '')
        title = title.replace('(', '')
        title = title.replace(')', '')
        title = title.replace('$', '')
        # Replacing some common TeX symbols.
        title = title.replace('\\"a', u'ä')
        title = title.replace('\\"o', u'ö')
        title = title.replace('\\"u', u'ü')
        title = title.replace('\\"A', u'Ä')
        title = title.replace('\\"O', u'Ö')
        title = title.replace('\\"U', u'Ü')
        # Clean up the title string.
        print('Searching for entry %d/%d...' % (k, n))
        try:
            bibtex_entry = _find_on_mathscinet(title)
        except:
            print('Entry \n\n%s\n\nnot found.' % title)
            # Write out the old entry to file.
            a = _get_string_representation(data.entries[bib_id])
            out.write('# The following entry could no be found on mathscinet.\n')
            out.write(a)
        else:
            print('found.')
            # Make sure that the BibTeX key remains identical.
            pattern = '(@[a-zA-Z]+\s*{)\w+'
            bibtex_entry = re.sub(pattern, r'\1%s' % bib_id, bibtex_entry)
            # Write it out to a file.
            out.write(bibtex_entry)
            success_count += 1
        out.write('\n\n')

    out.close()
    print('%d out of %d entries successfully converted.' % (success_count, n))

    return
# -----------------------------------------------------------------------------
def _get_string_representation(entry):
    '''String representation of BibTeX entry.
    '''
    lst = []
    lst.append('@%s{%s' % (entry.type, entry.key))
    for field, value in entry.fields.iteritems():
        lst.append('%s = {%s}' % (field, value))
    lst.append('}')

    return ',\n  '.join(lst)
# -----------------------------------------------------------------------------
def _read_bibtex(filename):

    from pybtex.database.input import bibtex

    # Open file for parsing.
    parser = bibtex.Parser()
    data = parser.parse_file(filename)

    return data
# -----------------------------------------------------------------------------
def _find_on_mathscinet(title):
    import requests

    url = 'http://www.ams.org/mathscinet/search/publications.html'

    # Typical search query line:
    # http://www.ams.org/mathscinet/search/publications.html?pg4=AUCN&s4=&co4=AND&pg5=TI&s5=ggg&co5=AND&pg6=PC&s6=&co6=AND&pg7=ALLF&s7=&co7=AND&Submit=Search&dr=all&yrop=eq&arg3=&yearRangeFirst=&yearRangeSecond=&pg8=ET&s8=All&review_format=html
    #
    payload = {'pg4': 'AUCN', 's4': '', 'co4': 'AND',
               'pg5': 'TI', 's5': title, 'co5': 'AND',
               'pg6': 'PC', 's6': '', 'co6': 'AND',
               'pg7': 'ALLF', 's7': '', 'co7': 'AND',
               'Submit': 'Search',
               'dr': 'all',
               'yrop': 'eq',
               'arg3': '',
               'yearRangeFirst': '',
               'yearRangeSecond': '',
               'pg8': 'ET',
               's8': 'All',
               'review_format': 'html',
               'fmt': 'bibtex' # immediately jump to BibTeX
               }
    r = requests.get(url, params=payload)
    assert(r.ok)

    # Find the BibTeX entry and extract it.
    import re
    a = '@[a-zA-Z]+\s*{'
    m = re.search(a, r.content)
    if not m:
        # Check if the website issues an error message.
        a = 'No publications results for'
        m = re.search(a, r.content)
        if m:
            raise RuntimeError('No publication results on mathscinet.')
        else:
            raise RuntimeError('Unknown error on mathscinet.')
    assert(m)

    # Find matching closing bracket.
    i0 = m.end()
    num_open_brackets = 1
    i1 = i0
    while num_open_brackets > 0:
        if r.content[i1] == '{':
            num_open_brackets += 1
        elif r.content[i1] == '}':
            num_open_brackets -= 1
        i1 += 1
    bibtex_entry = r.content[m.start():i1]

    return bibtex_entry
# -----------------------------------------------------------------------------
def _parse_cmd_arguments():
    import argparse

    parser = argparse.ArgumentParser(description='Improve BibTeX libraries.')
    parser.add_argument('infile',
                        type=str,
                        help='input BibTeX file')
    parser.add_argument('outfile',
                        type=str,
                        help='output BibTeX file')

    return parser.parse_args()
# -----------------------------------------------------------------------------
def _get_maps():
    tree = ET.parse('unicode.xml');
    root = tree.getroot()

    u2l = {}
    l2u = {}
    for char in root.iter('character'):
        try:
            uni = unichr(int(char.attrib['dec'])).encode('utf-8')
            for sub in char.iter('latex'):
                lat = sub.text
                u2l[uni] = lat
                l2u[lat] = uni
        except ValueError as e:
            pass
    return u2l, l2u
# -----------------------------------------------------------------------------
if __name__ == '__main__':
    _main()
# -----------------------------------------------------------------------------
