#!/usr/bin/env python
# -*- coding: utf8 -*-
#
import betterbib

import collections
from pybtex.database.input import bibtex
import re
import StringIO


def _main():
    args = _parse_cmd_arguments()
    infile = args.infile

    print('Reading from: %s' % infile)

    data = _read_bibtex(infile)
    n = len(data.entries)

    print('Number of entries: %d' % n)
    print('Saving to: %s' % args.outfile)
    print

    # Create the checkers.
    mathscinet = betterbib.MathSciNet()

    # Open output file for writing.
    out = open(args.outfile, 'w')

    # Write header to the output file.
    out.write(
        '%%comment{This file was created with BetterBib v%s.}' %
        betterbib.__version__
        )

    # Determine progress bar width according to the current console width.
    progress_bar = betterbib.ProgressBar(n)

    # Use an ordered dictionary to make sure that the entries are written out
    # sorted by their BibTeX key.
    od = collections.OrderedDict(sorted(data.entries.items()))

    k = 0
    success_count = 0
    change_count = 0
    for bib_id, entry in od.iteritems():
        k += 1
        b = entry.fields

        # Print a progress bar.
        # 73% [==========================>          ] 143
        progress_bar.show(k)

        # Clean up the title string.
        try:
            bibtex_entry = mathscinet.find(b)
        except RuntimeError as e:
            # print('Entry not found (\'%s\').' % e.message)
            # Write out the old entry to file.
            a = _get_string_representation(entry)
            out.write(
                '%%comment{Error when fetching the following entry (%s).}\n'
                % e.message
                )
            # This write operation may fail if `a` contains non-ASCII
            # characters. It's okay to fail too since this case requires some
            # human interaction anyways.
            try:
                out.write(a.encode('utf8'))
            except:
                # print('\nUnable to write the following entry to an '
                #       'ASCII-encoded file:\n\n %s\n' % a
                #       )
                raise
        else:
            # print('found.')
            # Check if the the fetched entry actually differs from what we
            # already had. This is for stats.
            parser = bibtex.Parser()
            parsed_bibtex = \
                parser.parse_stream(StringIO.StringIO(bibtex_entry))
            assert len(parsed_bibtex.entries) == 1
            entry = parsed_bibtex.entries[parsed_bibtex.entries.keys()[0]]

            if betterbib.adds_info(entry.fields, b):
                change_count += 1

            # Make sure that the BibTeX key remains identical.
            pattern = '(@[a-zA-Z]+)\s*{\w+'
            bibtex_entry = re.sub(pattern, r'\1{%s' % bib_id, bibtex_entry)
            # Write it out to a file.
            out.write(bibtex_entry)
            success_count += 1
        out.write('\n\n')

    out.close()
    print
    print
    print('Total number of entries: %d' % n)
    print('Found on MathSciNet:     %d' % success_count)
    print('Corrected entries:       %d' % change_count)
    return


def _get_string_representation(entry):
    '''String representation of BibTeX entry.
    '''
    lst = []
    lst.append('@%s{%s' % (entry.type, entry.key))
    for key, persons in entry.persons.items():
        persons_str = ' and '.join([_get_person_str(p) for p in persons])
        lst.append('%s = {%s}' % (key, persons_str))
    for field, value in entry.fields.iteritems():
        lst.append('%s = {%s}' % (field, value))
    lst.append('}')
    return ',\n  '.join(lst)


def _get_person_str(p):
    person_str = []
    for s in [' '.join(p.prelast() + p.last()),
              ' '.join(p.lineage()),
              ' '.join(p.first() + p.middle())]:
        if s:
            person_str.append(s)
    return ', '.join(person_str)


def _read_bibtex(filename):
    # Open file for parsing.
    parser = bibtex.Parser()
    data = parser.parse_file(filename)
    return data


def _parse_cmd_arguments():
    import argparse
    parser = argparse.ArgumentParser(
        description='Improve BibTeX libraries '
        'with information from online sources.'
        )
    parser.add_argument('infile',
                        type=str,
                        help='input BibTeX file')
    parser.add_argument('outfile',
                        type=str,
                        help='output BibTeX file')
    return parser.parse_args()


def _get_maps():
    tree = xml.etree.ElementTree.parse('unicode.xml')
    root = tree.getroot()

    u2l = {}
    l2u = {}
    for char in root.iter('character'):
        try:
            uni = unichr(int(char.attrib['dec'])).encode('utf-8')
            for sub in char.iter('latex'):
                lat = sub.text
                u2l[uni] = lat
                l2u[lat] = uni
        except ValueError:
            pass
    return u2l, l2u


def _preprocess_latex(s):
    # list: https://en.wikibooks.org/wiki/LaTeX/Special_Characters
    return re.sub(r'\\([\'"`\^\~=\.])([a-zA-Z])',
                  r'\\\1{\2}',
                  s)


if __name__ == '__main__':
    _main()
