#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
"""This tool is used for converting JabRef's journal name abbreviation files,
<https://github.com/JabRef/jabref/tree/master/src/main/resources/journals>,
into JSON.

Usage example:
```
cat IEEEJournalListText.txt journalList.txt | ./create_json - journals.json
```
"""
import argparse
import sys

import json


def _main():
    args = _parse_cmd_arguments()

    # read input file into dictionary
    out = {}
    for line in args.infile:
        sline = line.strip()
        if sline[0] == "#":
            continue
        k, v = sline.split("=")
        out[k.strip()] = v.strip()

    json.dump(out, args.outfile, indent=2)
    return


def _parse_cmd_arguments():
    parser = argparse.ArgumentParser(
        description="Creates YAML file from `=` input files."
    )
    parser.add_argument(
        "infile",
        nargs="?",
        type=argparse.FileType("r"),
        default=sys.stdin,
        help="input `=` files (default: stdin)",
    )
    parser.add_argument(
        "outfile",
        nargs="?",
        type=argparse.FileType("w"),
        default=sys.stdout,
        help="output YAML file (default: stdout)",
    )
    return parser.parse_args()


if __name__ == "__main__":
    _main()
